### ISSUE TITLE
Ques: Import Version in buildSrc/build.gradle.kts

### ISSUE THREAD

**Issue by kdani41** [nikhil-thakkar/multi-module-dependency-setup#5]
Thanks for this sample. I have quick question regarding [this](https://github.com/nikhil-thakkar/multi-module-dependency-setup/blob/master/buildSrc/build.gradle.kts#L16).

Is there any way to import [Versions.kt](https://github.com/nikhil-thakkar/multi-module-dependency-setup/blob/master/buildSrc/src/main/kotlin/Versions.kt) here?
So, we can write `implementation(Libs.blah)` 

Also don't we have to mention classpath dependencies in [buildscript block](https://github.com/nikhil-thakkar/multi-module-dependency-setup/blob/master/build.gradle.kts#L2)

**Comment by nikhil-thakkar** [comment]
@kdani41 Sorry for the late reply. Let me try to answer your questions.

> Is there any way to import Versions.kt here?

AFAIK this won't be possible given how `buildSrc` works. The entire folder is first compiled and added to classpath and hence different source files within `buildSrc` cannot reference each other. Please refer [here](https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:build_sources) for more information. 

> Also don't we have to mention classpath dependencies in buildscript block

No, its not required because in the end the same purpose is being achieved using `buildSrc`.
